name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

#name: Update main version
#run-name: Move ${{ github.event.inputs.major }} to ${{ github.event.inputs.target }}
#on:
#  workflow_dispatch:
#    inputs:
#      target:
#        description: The tag or reference to use
#        required: true
#      major:
#        type: choice
#        description: The major version to update
#        options:
#          - v1
#jobs:
#  tag:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Git config
#        run: |
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#      - name: Tag new target
#        run: git tag -f ${{ github.event.inputs.major }} ${{ github.event.inputs.target }}
#      - name: Push new tag
#        run: git push origin ${{ github.event.inputs.major }} --force